### ISSUE TITLE
Coud not build with Go 1.14

### ISSUE THREAD

**Issue by johndoe46** [greut/iiif#8]
Make deps was ok, but I couldn't build the server:

```
➜  iiif git:(master) make        
go build -o bin/iiif cmd/iiif.go
# github.com/greut/iiif/iiif
src/github.com/greut/iiif/iiif/image.go:170:23: cannot use ctx (type struct { vars map[string]string; config *Config }) as type context.Context in argument to thumbnails.Get:
	struct { vars map[string]string; config *Config } does not implement context.Context (missing Deadline method)
src/github.com/greut/iiif/iiif/server.go:30:91: cannot convert func literal (type func(<T>, string, groupcache.Sink) error) to type groupcache.GetterFunc
src/github.com/greut/iiif/iiif/server.go:31:12: undefined: groupcache.Context
src/github.com/greut/iiif/iiif/server.go:42:103: cannot convert func literal (type func(<T>, string, groupcache.Sink) error) to type groupcache.GetterFunc
src/github.com/greut/iiif/iiif/server.go:43:12: undefined: groupcache.Context
make: *** [Makefile:22: bin/iiif] Error 2
➜  iiif git:(master) go version
go version go1.14.2 linux/amd64
```

**Comment by kulwindermatharu** [comment]
**Same Issue**

**Comment by kulwindermatharu** [comment]
```
/root/go/src/Matharu/iiif/iiif/image.go:170:23: cannot use ctx (type struct { vars map[string]string; config *Config }) as type context.Context in argument to thumbnails.Get:
	struct { vars map[string]string; config *Config } does not implement context.Context (missing Deadline method)
/root/go/src/Matharu/iiif/iiif/server.go:30:91: cannot convert func literal (type func(<T>, string, groupcache.Sink) error) to type groupcache.GetterFunc
/root/go/src/Matharu/iiif/iiif/server.go:31:12: undefined: groupcache.Context
/root/go/src/Matharu/iiif/iiif/server.go:42:103: cannot convert func literal (type func(<T>, string, groupcache.Sink) error) to type groupcache.GetterFunc
/root/go/src/Matharu/iiif/iiif/server.go:43:12: undefined: groupcache.Context
```

**Comment by greut** [comment]
it's been a while since I've worked on it, not sure when will it be. Thanks for the issue though.
